= nasm: The Nock Assembler
Draft 1, 2023-08-01 ~ponnum-minnus <ernest.prabhakar@gmail.com>

== Introduction

`nasm` is an high-level assembly language for nock bytecode,
the foundational computing layer of the Urbit decentralized network.

It defines symbols, conventions, tools and libraries that make it easy
for Earthlings to read and write nock.

This document (and most of the examples) are directly inspired by
https://blog.timlucmiptev.space/part1.html[Nock for Everyday Coders].
Any errors or misinterpretaions are, of course, my sole responsibility.

=== Example

```hclang
; .nock <- `nock`;
; nock.assemble { [50, 51] (get 2) }
# [[50, 51], [0, 2]]
; nock.print .-1
# `[50 51] [0 2]`
; nock.eval .-2
# 50
 
```

=== Homoiconic C

`nasm` is written in Homoiconic C (also known as "hclang"),
another minimalist axiomatic language.
It has suprisingly similar semantics to nock,
but is designed to maximize readability and simplify evaluation.
Homoiconic C has no keywords, but instead uses very precise syntax:

- `;` for end of expressions (and the input prompt)
- `#` for comments (and the output prompt)
- `[square brackets]` for comma-seperated lists ("boxed" grouping)
- `(round brackets)` for expressions ("unboxed" grouping)
- `{curly brackets}` for closures ("lazy" evaluation)
- `.name value` to assign (immutable) variables
- `<-` to load modules
- `backticks` ("`") for strings

=== Compiling to Assembly

While hclang is an impure systems language
(inspired by https://github.com/repos-bitc/bitc[bitc-lang]),
it includes a pure subset that can be compiled to Nock assembly:

```hclang
; [50, 51].0
# 50
; nock.compile { [50, 51] .0 }
# { [50, 51] (get 2) }
```

=== Shortcuts

For brevity, we use the following abbreviations:

```hclang
; .nasm nock.assemble;
; .nc nock.compile;
; .eval nock.eval;
; .run { eval (nasm _) }
; .pp { nock.print (nasm _) } # pretty-print assembly
```

Where `_` is the default argument for a closure

This allows us to rewrite the initial example as:

```hclang
; run { [50, 51] (get 2) }
# 50
```

== Primitive Operators

```hclang
.get 0 # '/'
.is-cell 3 # '?'
.increment 4 # '+'
.is-equal 5 # '='
.set 100 # '#'
.eval 102 # '*'
```

The Nock [pseudocode notation](https://developers.urbit.org/reference/nock/definition#rules)
defines six prefix operators: ?, +, =, /, #, and *.

Nasm instantiates these as actual operators with actual names
(while I sympathize with the desire to avoid English cultural imperialism,
I find explicit words very helpful in the learning process).

Note that eval and set are assigned 1xx psuedo-opcodes, as are other non-coded operations.
These simplify composition, but are "compiled away" by the assembler.
See Appendix A for more details.


=== Examples

```hclang
; run { 50 (get 1) }
# 50
; run { [50, 51] (get 2) }
# 50
; run { 50 (is-cell (get 1)) }
# 1 (false)
; run { [50] (is-cell (get 1)) }
# 0 (true)
; run { 50 (increment (get 1)) }
# 51
; run { [50, 51] (is-equal (get 2) (get 2)) }
# 0 (true)
; run { [50, 51] (is-equal (get 2) (get 3)) }
# 1 (false)
; run { 50 (set 2 [8, 9, 10]) }
# [50, [9, 10]]
; run { eval (50 (get 1))}
# 50
```

=== Hierarchical `get`

The `get` opcode in nock extracts items from a binary tree
(which is what all lists are implemented as in nock)

```hclang
; run { list (get 2) }
# 10
; run { list (get 5) }
# [12, 13]
```

For convenience, you can pass `get` a 0-based list of nested indices
(rather than a number) which it will use to calculate the appropriate offset:

```hclang
; .list2 [20, 21, [22, 23]];
; list2 .0
# 20
; list2 .2 .1
# 23
; nc {list2 .2 .1}
# { [20, [21, [22, 23]]] (get [1, 1, 1]) } # 8, I think
; eval .-1
# 23
```

== Quoting and Evaluation

=== OpCode 1: quote

The `quote` opcode ignores the subject and returns its body:

```hclang
; nasm { [50, 51] (quote get 2) }
# [[50, 51], [1, [0, 2]]]
; eval .-1
# [0, 2]
```

Note that the assembler stil expands variable names inside a quote,
such as `get`.

You can get the same effect by passing an hclang closure:

```hclang
; nasm { [50, 51] {get 2} }
# [[50, 51], [1, [0, 2]]]
```

Observe that the eval pseudo-app acts as the inverse of quote,
and may be expanded by the assembler:

```hclang
; nasm { [50, 51] (eval {get 2}) }
# [[50, 51], [0, 2]]
```

=== OpCode 7: compose

The simplest native evaluation opcode is `compose`,
which repeatedly applies its arguments to the subject:

```hclang
; nasm { [23, 45] (compose (get 3) (incr (get 1))) }
# { [23, 45], [7, [0, 3], [4, 0, 1]] }
; eval .-1
# 46
```

Because hclang supports linear lists as well as binary expressions,
you can also just specify a sequence of operations directly,
and nasm will interpolate the 7.

```hclang
; nasm { [23, 45] (get 3) (incr (get 1)) }
# { [23, 45], [7, [0, 3], [4, 0, 1]] }
; eval .-1
# 46
```

=== OpCode 2: map-eval

OpCode 2 is the more general version of 7
(more precisely, 7 is syntactic sugar on 2).
It evaluates *both* arguments against the subject
before applying them.

```hclang
; [(incr (get 1)), 51] [map-eval (get 3) (get 2)]
# [[[4, 0, 1], 51], [2, [0, 3] [0, 2]]]
; eval .-1
# 52
# Original: { [[4, 0, 1], 51] [2, [0, 3] [0, 2]] }
# Effect: { 51 (incr (get 1)) }
```

=== OpCode 9: call

```hclang

# Original: [50 51] [2 [0 3] [1 [4 0 1]]]
# [23 45] [7 [0 3] [4 0 1]]
```




```hclang
# Other OpCodes

.quote 1
.map-eval 2
.if-else 6
.compose 7
.prepend 8
.call 9
.hint 11

# Other Pseudo-Operators

.map 121
.reduce 122
.if 161
.else 162
.insert 181
.delete 182
```

=== A Note on Variables

The assembler has access to local context, so it can access and expand variables.

```hclang
; .list [10, 11, 12, 13];
; nasm { list }
# [10, [11, [12, 13]]]
```

The local context itself is represented by '.',
which nasm models as an implicit get:

```hclang
; nasm { . }
# {0 1}
```


By default, the compiler will also expand variables:

```hclang
; nc { list (get 1) }
# { [10, [11, [12, 13]]] (0 1) }
```

We can instead tell the compiler to include an environment
as part of its output.
That tells it to not expand those variables,
but instead pass along the environmnet for the assembler to use.


```hclang
; .ops = nock.opcodes;
; nc.pass { ops }
; nc { [50, 51] (get 2) }
# {.. ops; [50, 51] [get, 2] }
; run .-1
# 50
```

The `..` operator sets the parent of the current context to 
the (immutable) variable ops, so nasm knows it can make use of it.



=== Interlude: Map and Reduce

The easiest way for me to understand nock opcode 2 is in terms of
two hclang primitive operators: map `&` and reduce `|`.

==== Map

Map creates a new list from an old list by applying a closure in parallel:

```hclang
; [1, 2] & {pp _} 
# [`1`, `2`]
```

==== Reduce

Reduce creates a single element from an old list by repeated application to a seed.
For example, when you apply an element to a list it appends (repeatedly):

```hclang
; [] 1
# [1]
; [1] 2
# [1, 2]
; [1, 2] 3 4
# [1, 2, 3, 4]
```

We can use this (rather awkwardly) to clone a list using Reduce:

```hclang
; [1, 2, 3, 4] | []
# [1, 2, 3, 4]
```

Compared to wrapping each element if we instead used Map:


```hclang
; [1, 2, 3, 4] & []
# [[1], [2], [3], [4]]
```

==== Evaluation

Importantly, Reduce is how hclang performs evaluation.

Consider `nock.print` of a cell:

```hclang
; nock.print [1, 2]
# `[1 2]`
```

We can implement it as either a closure to apply:


```hclang
; .np_closure { nock.print [1, 2] };
; np_closure()
# `[1 2]`
```

or a list of elements to apply:


```hclang
; .np_list [ nock, .print, [1, 2] ];
; np_list | ()
# `[1 2]`
```

==== Applications of nil

Note that applying any element to nil results in that element:

```hclang
; () 1
# 1
```

Applying nil a to non-closure just returns that element:

```hclang
; 1 ()
# 1
```


Applying nil to a closure evaluates it:


```hclang
; { 1 } ()
# 1
```

=== OpCode 2: map-eval


```hclang
; .op2 { [50, 51] [2, [0, 3], [1, [4, 0, 1]]] }
; .op2a { [50, 51] [map-eval (get 3) {incr get 1}] }

# Break it down into map:
; { (get 3), {incr get 1} } & [50, 51] 
# { 51 (incr get 1) }

# Then eval:
; pp { 51 (incr get 1) }
# `52`
```

To simplify compilation into this opcode, nock defines a new '&|' operator:

```hclang
; [1, 2] nock.&| []
# [1, [2]]
# From: [[1], [2]] | ()

; nc { [(get 3), {incr get 1} ] &| [50, 51] }
# { [50, 51] [map-eval (get 3) {incr get 1}] }
```


== Appendix A: RINC Pseudo-Ops

Strictly speaking, nasm is actually designed around the small number
of primitive operations that are used to define nock,
rather than the actual nock opcodes.
This also makes it easy to compile hclang primitives down to the
corresponding psuedo-op.

This approach is similar to the way modern processors and compilers
tend to use orthogonal Reduced Instruction Set Computing (RISC) operations,
rather the Complex Instruction Set Computing (CISC) operations
optimized for efficient hand-coding.
Hence the term "RINC", for Reduced Instruction Nock Computing.

The nasm assembler is repsonsible for converting any pseudo-ops
into the appropriate nock opcodes, so the resulting code runs
on any nock-compatible virtual machine.

```hclang
.opcodes [

    # Primitive Operators

    .is-cell 3 # '?'
    .increment 4 # '+'
    .is-equal 5 # '='
    .get 0 # '/'
    .set 10 # '#'
    .eval 100 # '*'

    # Other OpCodes

    .quote 1
    .map-eval 2
    .if-else 6
    .compose 7
    .prepend 8
    .call 9
    .hint 11

    # Other Pseudo-Operators

    .map 121
    .reduce 122
    .if 161
    .else 162
    .insert 181
    .delete 182
]
```
