version: '2.1'
orbs:
  node: circleci/node@4.7.0
jobs:
  install-node:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          install-yarn: true
      - run: node --version
  test-mocha:
    steps:
      - mocha test --reporter mocha-junit-reporter:
          environment:
            MOCHA_FILE: $CIRCLE_TEST_REPORTS/junit/test-results.xml
workflows:
  test_igwet:
    jobs:
      - test-mocha
