= Zoasophy 202: Artificial Emotion
:Author: Ernest Prabhakar
:Date: 2023-01-29
:Version: 0.9.0

While the digerati (including me) have been fascinated by
https://www.theatlantic.com/technology/archive/2022/12/openai-chatgpt-writing-high-school-english-essay/672412/[ChatGPT]
and Artificial Intelligence,
I've been wondering why I can't find any good models of Artificial Emotion.
Even if you take the ultra-rationalist position of "Intellect Good, Emotions Bad,"
surely it would be important to understand the enemy!

Most traditional models of emotion focus on "four Fs": fight, flight, feed, mate.
However, it occurred to me that a key aspect of emotion is actually energy management:
we get excited or aroused when something important might happen, and sad or bored when it does not.

Intriguingly, this suggests treating "power management" in battery-dependent computers as a sort of proto-emotion.
Even better, that enables new to reuse my energy-conserving Ents from 201 as the basis of another toy model,
to see what insights we might glean.

== A Bit of Emotion

The simplest model for an Ent assumes they can be in one of two states: "A" for aroused and "B" for bored.  

```
.Internal <.A, .B>
```

Similarly, the World can be in two states, "X" for eXciting and "Y" for Yawn-inducing

```
.External <.X, .Y>
```

The natural response is for My Emotions (.ME) to only be aroused when the world is exciting:

```
.Response ^ (.World External) {
    .ME (World == .X) ? .A : .B
}
```

== Conservation of Energy

This allows us to simulate "what" an emotion does, but doesn't provide insight about "why."
For that we need to introduce the idea of Energy over Time
(the tuple of (Energy, Time) is sometimes called Action).

For simplicity, we model Time as a discrete series of uniform "Ticks."  
Different internal states cause an Ent to *lose* a certain amount of Energy per Tick,
say 5 if Aroused versus 1 if Bored

```
.E_lose (.A 5, .B 1)
```

Conversely, different external states cause an Ent to *gain* energy,
though the precise amount depends on the internal state:

```
.E_gain (
  .A (.X 10, .Y 2)
  .B (.X 1, .Y 0)
)
```
Thus, the Energy per Tick is a function of both the internal and external state:

```
.E_tick ^(.Ent Internal, .World External) {
  (E_gain Ent World) - (E_lose Ent)
}
```
Thus being Aroused is energy-positive when the World is eXciting:

```
; E_tick(.A, .X) # 10 - 5
# 5
; E_tick(.A, .Y) # 2 - 5
# -3
```

While being Bored is a best neutral:
```
; E_tick(.B, .X) # 1 - 1
# 0
; E_tick(.B, .Y) # 0 - 1
# -1

```
As a result, the Ent only gains Energy if it is Aroused when the world is eXciting.
Otherwise it is better to be Bored.


== Selective Populations

The final piece of the puzzle is that there has to be something at stake.
The simplest rule is that organisms that gain enough energy reproduce,
while those that lose too much energy die.

We can imagine four types of Responses to the External world:

```
# always Aroused
.EntAA ^ (.World External) {
    .ME (.A)
}

# always Bored
.EntBB ^ (.World External) {
    .ME (.B)
}

# Aroused IFF eXciting
.EntAB ^ (.World External) {
    .ME (World == .X) ? .A : .B
}

# Bored IFF eXciting
.EntBA ^ (.World External) {
    .ME (World == .X) ? .B : .A
}
```

It should be obvious that, as long as there is some randomoness in the external environment,
only `.EntAB` is adaptive.

Things get even more interesting if increase the variability.
We can imagine each descendants of EntAB has a different levels of Arousal,
with some paying a higher cost but capturing more energy
(think carnivores or flyuing insects as compared to herbivorses or crawlers).
These high-achievers will flourish in an energy-rich environment, but die off in lean times.

== From Energy to Matter

At first blush, this one-bit model only seems applicable to plants.
It is a plausible explanation of why flowers open during the day,
or why seedlings sprout in the spring.

However, the same one-bit model could also apply to carnivores,
who get activated when prey approaches, but are otherwise lethargic.
In such a world, prey would need a two-bit model
where eagerness for food (move forward) is balanced with fear of predators (move backward).
It does no good to gain energy and price of losing matter (by becoming someone else's lunch).

This simple model seems like it could be scaled up to explain arbitrarily complex behavior.
Each bit can be thought of as a switch that connects external stimuli to a specific action,
and those actions have evolutionary consequences.
Presumably there are also higher-order bits, that respond to internal rather than external stimuli
(e.g., feeling ashamed of being afraid).
Maternal and social animals would need to have multiple 'ME's to optimize against,
perhaps giving rise to what Adam Smith calls "moral sentiments."

== Future Work

A logical next step would be to map this onto traditional models of emotion (e.g., https://positivepsychology.com/emotion-wheel/[Plutchik's Emotion Wheel)] to see how few bits could plausible represent them.

