#!/usr/bin/env -S deno run -A

/**
 * Install git hooks
 *
 * This script:
 * 1. Validates configuration exists
 * 2. Creates .git/hooks/ directory if needed
 * 3. Generates shell wrapper scripts for each configured hook
 * 4. Makes scripts executable
 */

import { ensureDir } from "@std/fs";
import { loadConfig } from "./config.ts";
import { getGitRoot } from "./files.ts";

/**
 * Install git hooks
 */
export async function install(): Promise<void> {
  console.log("🦕 Installing Deno Hooks...\n");

  // Get git root
  const gitRoot = await getGitRoot();
  console.log(`📁 Git root: ${gitRoot}`);

  // Load and validate configuration
  const config = await loadConfig(gitRoot);
  const hookNames = Object.keys(config.hooks);
  console.log(`📋 Found ${hookNames.length} hook(s): ${hookNames.join(", ")}`);

  // Ensure .git/hooks/ exists
  const hooksDir = `${gitRoot}/.git/hooks`;
  await ensureDir(hooksDir);

  // Install each hook
  for (const hookName of hookNames) {
    await installHook(gitRoot, hooksDir, hookName);
  }

  console.log("\n✅ Installation complete!");
  console.log("\nGit hooks are now active. They will run automatically on:");
  for (const hookName of hookNames) {
    console.log(`  - ${hookName}`);
  }
}

/**
 * Install a single git hook
 */
async function installHook(
  gitRoot: string,
  hooksDir: string,
  hookName: string,
): Promise<void> {
  const hookPath = `${hooksDir}/${hookName}`;

  // Generate shell script
  const script = generateHookScript(gitRoot, hookName);

  // Write script
  await Deno.writeTextFile(hookPath, script);

  // Make executable (Unix only - Windows uses git's shell)
  if (Deno.build.os !== "windows") {
    await Deno.chmod(hookPath, 0o755);
  }

  console.log(`  ✓ Installed ${hookName}`);
}

/**
 * Generate shell wrapper script for a hook
 */
function generateHookScript(gitRoot: string, hookName: string): string {
  // Use #!/bin/sh for maximum portability
  return `#!/bin/sh
# Generated by deno-hooks - DO NOT EDIT
# To update, run: deno run -A deno-hooks/install.ts

exec deno run -A "${gitRoot}/deno-hooks/run.ts" "${hookName}" "$@"
`;
}

// Run if called directly
if (import.meta.main) {
  try {
    await install();
  } catch (error) {
    console.error("\n❌ Installation failed:", error.message);
    Deno.exit(1);
  }
}
