name: Deno CI

on:
    push:
        branches: ["master"]
        tags: ["v*"]
    pull_request:
        branches: ["master"]

jobs:
    build:
        permissions:
            contents: read
            packages: write
            id-token: write

        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Use Deno 2.x
              uses: denoland/setup-deno@v2
            - run: deno install
            - run: deno task test
            - name: Publish to Deno.land
              id: deno-publish
              if: github.ref == 'refs/heads/master'
              run: deno publish
            - name: Create release on publish
              uses: ncipollo/release-action@v1
              if: github.ref == 'refs/heads/master'
              with:
                  tag: ${{ github.ref_name }}
                  generateReleaseNotes: true
                  skipIfReleaseExists: true
