# This workflow will do a clean installation of Deno dependencies, cache/restore them, build the source code and run tests across different versions of Deno

name: Deno CI

on:
  push:
    branches: ["master", "221-deno-publish"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    permissions:
      contents: read
      packages: write
      id-token: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Deno 2.x
        uses: denoland/setup-deno@v2
      - run: deno install
      - run: deno task test
      - name: Publish to Deno.land
        id: deno-publish
        if: github.ref == 'refs/heads/221-deno-publish' && github.event_name == 'push'
        run: deno publish
      - name: Create release on publish
        uses: ncipollo/release-action@v1
        if: ${{ steps.deno-publish.outputs.type == 'published' }}
