# This workflow will do a clean installation of Deno dependencies, cache/restore them, build the source code and run tests across different versions of Deno

name: Deno CI

on:
  push:
    branches: ["master"]
    tags: ["v*"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    permissions:
      contents: write
      packages: write
      id-token: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Deno 2.x
        uses: denoland/setup-deno@v2
      - run: deno install
      - run: deno task build
      - run: deno task test
      - name: Create release on tag
        uses: ncipollo/release-action@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag: ${{ github.ref_name }}
      - name: Publish to Deno.land on merge to master
        id: deno-publish
        if: github.ref == 'refs/heads/master'
        run: deno task publish
        env:
          DENO_AUTH_TOKEN: ${{ secrets.DENO_AUTH_TOKEN }}
