name: Deno CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    permissions:
      contents: read
      packages: write
      id-token: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Deno 2.x
        uses: denoland/setup-deno@v2
      - run: deno install
      - run: deno task test
      - name: Publish to Deno.land
        id: deno-publish
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: |
          deno publish
          echo "::set-output name=publish-output::$(deno publish)"
      - name: Echo Deno publish output
        run: echo "${{ steps.deno-publish.outputs.publish-output }}"
      - name: Create release on publish
        uses: ncipollo/release-action@v1
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
