// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $index from "./routes/index.tsx";
import * as $test from "./routes/local.tsx";
import * as $Main from "./islands/Main.tsx";
import * as $Executor from "./islands/Executor.tsx";
import * as $Historian from "./islands/Historian.tsx";
import * as $Reset from "./islands/Reset.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/index.tsx": $index,
    "./routes/test.tsx": $test,
  },
  islands: {
    "./islands/Main.tsx": $Main,
    "./islands/Executor.tsx": $Executor,
    "./islands/Historian.tsx": $Historian,
    "./islands/Reset.tsx": $Reset,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
